name: github pages

on:
  schedule:
    - cron:  '30 1,5,9,13 * * MON-FRI'
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true
      - name: FetchData
        run: |
          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d @pr_fe.json https://api.github.com/graphql > data/PR_FE.json
          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d @pr_ct.json https://api.github.com/graphql > data/PR_CT.json
          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d @pr_rt.json https://api.github.com/graphql > data/PR_RT.json
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
